//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

// KLAR ** G-NIVÅ ** KLAR
###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "6419af28665a11660b32cc0c"
}

// KLAR ** G-NIVÅ ** KLAR
###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "elin horn",
  "email": "elin@mail.com",
  "password": "elin"
}

// KLAR ** G-NIVÅ ** KLAR
###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "elin@mail.com",
  "password": "elin"
}

// KLAR ** G-NIVÅ ** KLAR
###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

// KLAR ** G-NIVÅ ** KLAR
###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/6419ae30665a11660b32cc0a

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Chips",
  "description": "Pringels hot spicy",
  "price": 23, 
  "lager": 54
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "64197076307fff84c4192e95", 
      "products": [
    {
      "productId": "6419ae30665a11660b32cc0a", 
      "quantity": 2
    },
    {
      "productId": "6419acc9665a11660b32cc09",
      "quantity": 5
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###